app = 't3-act8-eq14'
primary_region = 'iad'

[build]

[env]
  PORT = "8080"

[processes]
  app = "npm run build && npm run start"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']